import type { Package, Category } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'AI Feedback', slug: 'ai-feedback', description: 'Get LLM-powered design reviews, layout suggestions, and automated critiques' },
  { id: 'cat-2', name: 'Visual Editing', slug: 'visual-editing', description: 'Tweak styles, tokens, and layout directly on the canvas' },
  { id: 'cat-3', name: 'Inspection', slug: 'inspection', description: 'Inspect elements, spacing, box model, and computed styles' },
  { id: 'cat-4', name: 'Annotation', slug: 'annotation', description: 'Mark up designs, leave comments, and sync feedback to issues' },
  { id: 'cat-5', name: 'Testing & QA', slug: 'testing-qa', description: 'Run accessibility audits, visual regression checks, and project validations' },
  { id: 'cat-6', name: 'Theming', slug: 'theming', description: 'Switch themes, compare token sets, and manage design tokens' },
  { id: 'cat-7', name: 'Spec & Handoff', slug: 'spec-handoff', description: 'Extract specs, generate docs, and bridge designs to code' },
  { id: 'cat-8', name: 'Deploy', slug: 'deploy', description: 'Ship prototypes and apps to staging and production' },
  { id: 'cat-9', name: 'CLI Control', slug: 'cli-control', description: 'Scaffold, build, and manage plugins from the command line' },
];

const now = new Date().toISOString();

const DC_ORG = { id: 'a-1', github_username: 'design-canvas', display_name: 'Design Canvas', avatar_url: 'https://avatars.githubusercontent.com/u/140754480?s=40', github_url: 'https://github.com/design-canvas', is_org: true };
const COMMUNITY_1 = { id: 'a-2', github_username: 'jmorrow', display_name: 'Jake Morrow', avatar_url: 'https://avatars.githubusercontent.com/u/12345678?s=40', github_url: 'https://github.com/jmorrow', is_org: false };
const COMMUNITY_2 = { id: 'a-3', github_username: 'studiolab', display_name: 'Studio Lab', avatar_url: 'https://avatars.githubusercontent.com/u/23456789?s=40', github_url: 'https://github.com/studiolab', is_org: true };
const COMMUNITY_3 = { id: 'a-4', github_username: 'anakoles', display_name: 'Ana Koles', avatar_url: 'https://avatars.githubusercontent.com/u/34567890?s=40', github_url: 'https://github.com/anakoles', is_org: false };

export const MOCK_PACKAGES: Package[] = [
  // — AI Feedback —
  {
    id: 'pkg-1', name: 'copilot-review', scope: 'design-canvas',
    description: 'Get instant LLM feedback on your UI — layout critique, copy suggestions, and component recommendations.',
    category_id: 'cat-1', author_id: 'a-1',
    tags: ['ai', 'review', 'llm', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/copilot-review',
    repo_url: 'https://github.com/design-canvas/copilot-review',
    docs_url: 'https://docs.designcanvas.dev/plugins/copilot-review', issues_url: null,
    weekly_downloads: 14_300, github_stars: 1_100,
    bundle_size_gzip: 22_500, license: 'Apache-2.0', has_types: true,
    open_issues_count: 31, latest_version: '0.9.4',
    last_published_at: '2026-04-28T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[0],
    author: DC_ORG,
  },
  {
    id: 'pkg-2', name: 'ai-alt-text', scope: 'design-canvas',
    description: 'Auto-generate alt text and ARIA labels for images and icons using vision models.',
    category_id: 'cat-1', author_id: 'a-4',
    tags: ['ai', 'a11y', 'alt-text', 'vision'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/ai-alt-text',
    repo_url: 'https://github.com/anakoles/dc-ai-alt-text',
    docs_url: null, issues_url: null,
    weekly_downloads: 4_200, github_stars: 190,
    bundle_size_gzip: 8_900, license: 'MIT', has_types: true,
    open_issues_count: 7, latest_version: '1.0.2',
    last_published_at: '2026-04-18T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[0],
    author: COMMUNITY_3,
  },

  // — Visual Editing —
  {
    id: 'pkg-3', name: 'style-editor', scope: 'design-canvas',
    description: 'Edit element styles visually with token support — colors, spacing, typography, and shadows.',
    category_id: 'cat-2', author_id: 'a-1',
    tags: ['style', 'editor', 'tokens', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/style-editor',
    repo_url: 'https://github.com/design-canvas/style-editor',
    docs_url: 'https://docs.designcanvas.dev/plugins/style-editor', issues_url: null,
    weekly_downloads: 31_200, github_stars: 890,
    bundle_size_gzip: 14_100, license: 'MIT', has_types: true,
    open_issues_count: 11, latest_version: '2.3.0',
    last_published_at: '2026-04-22T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[1],
    author: DC_ORG,
  },
  {
    id: 'pkg-4', name: 'color-picker', scope: 'design-canvas',
    description: 'Advanced color picker with palettes, gradients, contrast checking, and eyedropper support.',
    category_id: 'cat-2', author_id: 'a-2',
    tags: ['color', 'picker', 'contrast', 'palette'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/color-picker',
    repo_url: 'https://github.com/jmorrow/dc-color-picker',
    docs_url: null, issues_url: null,
    weekly_downloads: 9_400, github_stars: 340,
    bundle_size_gzip: 11_800, license: 'MIT', has_types: true,
    open_issues_count: 12, latest_version: '2.0.1',
    last_published_at: '2026-03-30T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[1],
    author: COMMUNITY_1,
  },

  // — Inspection —
  {
    id: 'pkg-5', name: 'inspector', scope: 'design-canvas',
    description: 'Inspect element styles, spacing, box model, and computed properties on any page element.',
    category_id: 'cat-3', author_id: 'a-1',
    tags: ['inspect', 'spacing', 'box-model', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/inspector',
    repo_url: 'https://github.com/design-canvas/inspector',
    docs_url: 'https://docs.designcanvas.dev/plugins/inspector', issues_url: null,
    weekly_downloads: 38_500, github_stars: 1_420,
    bundle_size_gzip: 18_200, license: 'MIT', has_types: true,
    open_issues_count: 9, latest_version: '3.1.2',
    last_published_at: '2026-04-25T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[2],
    author: DC_ORG,
  },

  // — Annotation —
  {
    id: 'pkg-6', name: 'github-issues', scope: 'design-canvas',
    description: 'Pin annotations to the canvas and sync them directly to GitHub Issues for tracking.',
    category_id: 'cat-4', author_id: 'a-1',
    tags: ['annotation', 'github', 'issues', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/github-issues',
    repo_url: 'https://github.com/design-canvas/github-issues',
    docs_url: 'https://docs.designcanvas.dev/plugins/github-issues', issues_url: null,
    weekly_downloads: 18_600, github_stars: 720,
    bundle_size_gzip: 6_400, license: 'MIT', has_types: true,
    open_issues_count: 8, latest_version: '1.6.0',
    last_published_at: '2026-04-20T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[3],
    author: DC_ORG,
  },
  {
    id: 'pkg-7', name: 'redline', scope: 'design-canvas',
    description: 'Draw redline annotations with measurement overlays — mark spacing, alignment, and sizing issues.',
    category_id: 'cat-4', author_id: 'a-3',
    tags: ['redline', 'markup', 'measure', 'annotation'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/redline',
    repo_url: 'https://github.com/studiolab/dc-redline',
    docs_url: null, issues_url: null,
    weekly_downloads: 6_700, github_stars: 310,
    bundle_size_gzip: 9_200, license: 'MIT', has_types: true,
    open_issues_count: 5, latest_version: '1.2.0',
    last_published_at: '2026-04-15T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[3],
    author: COMMUNITY_2,
  },

  // — Testing & QA —
  {
    id: 'pkg-8', name: 'a11y-checker', scope: 'design-canvas',
    description: 'Audit page accessibility against WCAG guidelines — contrast, landmarks, ARIA, and keyboard navigation.',
    category_id: 'cat-5', author_id: 'a-1',
    tags: ['a11y', 'wcag', 'audit', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/a11y-checker',
    repo_url: 'https://github.com/design-canvas/a11y-checker',
    docs_url: 'https://docs.designcanvas.dev/plugins/a11y-checker', issues_url: null,
    weekly_downloads: 22_000, github_stars: 940,
    bundle_size_gzip: 28_400, license: 'MIT', has_types: true,
    open_issues_count: 14, latest_version: '2.1.0',
    last_published_at: '2026-04-24T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[4],
    author: DC_ORG,
  },
  {
    id: 'pkg-9', name: 'checks', scope: 'design-canvas',
    description: 'Run project checks and associate them with components — lint, token usage, and naming conventions.',
    category_id: 'cat-5', author_id: 'a-1',
    tags: ['checks', 'lint', 'validation', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/checks',
    repo_url: 'https://github.com/design-canvas/checks',
    docs_url: 'https://docs.designcanvas.dev/plugins/checks', issues_url: null,
    weekly_downloads: 28_700, github_stars: 650,
    bundle_size_gzip: 4_100, license: 'MIT', has_types: true,
    open_issues_count: 3, latest_version: '1.4.1',
    last_published_at: '2026-04-12T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[4],
    author: DC_ORG,
  },

  // — Theming —
  {
    id: 'pkg-10', name: 'theme-switcher', scope: 'design-canvas',
    description: 'Switch between Fluent theme presets and preview your UI in light, dark, and high-contrast modes.',
    category_id: 'cat-6', author_id: 'a-1',
    tags: ['theme', 'switcher', 'dark-mode', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/theme-switcher',
    repo_url: 'https://github.com/design-canvas/theme-switcher',
    docs_url: 'https://docs.designcanvas.dev/plugins/theme-switcher', issues_url: null,
    weekly_downloads: 42_000, github_stars: 1_850,
    bundle_size_gzip: 3_200, license: 'MIT', has_types: true,
    open_issues_count: 4, latest_version: '2.4.0',
    last_published_at: '2026-04-26T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[5],
    author: DC_ORG,
  },
  {
    id: 'pkg-11', name: 'theme-diff', scope: 'design-canvas',
    description: 'Compare Fluent theme token sets side-by-side — spot differences in color, spacing, and typography.',
    category_id: 'cat-6', author_id: 'a-1',
    tags: ['theme', 'diff', 'tokens', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/theme-diff',
    repo_url: 'https://github.com/design-canvas/theme-diff',
    docs_url: 'https://docs.designcanvas.dev/plugins/theme-diff', issues_url: null,
    weekly_downloads: 5_800, github_stars: 280,
    bundle_size_gzip: 1_900, license: 'MIT', has_types: true,
    open_issues_count: 2, latest_version: '1.1.0',
    last_published_at: '2026-03-20T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[5],
    author: DC_ORG,
  },

  // — Spec & Handoff —
  {
    id: 'pkg-12', name: 'blueprint', scope: 'design-canvas',
    description: 'Extract visual specs from any URL, map to Fluent tokens, and generate a structured design brief.',
    category_id: 'cat-7', author_id: 'a-1',
    tags: ['spec', 'extract', 'blueprint', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/blueprint',
    repo_url: 'https://github.com/design-canvas/blueprint',
    docs_url: 'https://docs.designcanvas.dev/plugins/blueprint', issues_url: null,
    weekly_downloads: 11_200, github_stars: 530,
    bundle_size_gzip: 15_600, license: 'MIT', has_types: true,
    open_issues_count: 18, latest_version: '1.4.0',
    last_published_at: '2026-04-22T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[6],
    author: DC_ORG,
  },
  {
    id: 'pkg-13', name: 'storybook-bridge', scope: 'design-canvas',
    description: 'Audit page components against Storybook and generate a coverage report with missing stories.',
    category_id: 'cat-7', author_id: 'a-3',
    tags: ['storybook', 'audit', 'coverage', 'handoff'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/storybook-bridge',
    repo_url: 'https://github.com/studiolab/dc-storybook-bridge',
    docs_url: null, issues_url: null,
    weekly_downloads: 3_800, github_stars: 160,
    bundle_size_gzip: 7_200, license: 'MIT', has_types: true,
    open_issues_count: 6, latest_version: '0.9.1',
    last_published_at: '2026-04-10T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[6],
    author: COMMUNITY_2,
  },
  {
    id: 'pkg-14', name: 'designmd-generator', scope: 'design-canvas',
    description: 'Generate and edit DESIGN.md — define your visual language, tokens, and component inventory in one doc.',
    category_id: 'cat-7', author_id: 'a-2',
    tags: ['design-doc', 'markdown', 'spec', 'handoff'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/designmd-generator',
    repo_url: 'https://github.com/jmorrow/dc-designmd',
    docs_url: null, issues_url: null,
    weekly_downloads: 2_900, github_stars: 120,
    bundle_size_gzip: 4_800, license: 'MIT', has_types: true,
    open_issues_count: 3, latest_version: '1.0.0',
    last_published_at: '2026-04-05T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[6],
    author: COMMUNITY_1,
  },

  // — Deploy —
  {
    id: 'pkg-15', name: 'azure-swa', scope: 'design-canvas',
    description: 'Create and manage Azure Static Web Apps via az CLI — deploy prototypes straight from the canvas.',
    category_id: 'cat-8', author_id: 'a-1',
    tags: ['deploy', 'azure', 'swa', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/azure-swa',
    repo_url: 'https://github.com/design-canvas/azure-swa',
    docs_url: 'https://docs.designcanvas.dev/plugins/azure-swa', issues_url: null,
    weekly_downloads: 8_900, github_stars: 420,
    bundle_size_gzip: null, license: 'MIT', has_types: true,
    open_issues_count: 4, latest_version: '1.2.0',
    last_published_at: '2026-04-10T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[7],
    author: DC_ORG,
  },

  // — CLI Control —
  {
    id: 'pkg-16', name: 'cli', scope: 'design-canvas',
    description: 'The Design Canvas CLI — scaffold, develop, build, and publish plugins from your terminal.',
    category_id: 'cat-9', author_id: 'a-1',
    tags: ['cli', 'scaffold', 'build', 'official'],
    npm_url: 'https://www.npmjs.com/package/@design-canvas/cli',
    repo_url: 'https://github.com/design-canvas/cli',
    docs_url: 'https://docs.designcanvas.dev/cli', issues_url: null,
    weekly_downloads: 38_500, github_stars: 1_420,
    bundle_size_gzip: null, license: 'MIT', has_types: true,
    open_issues_count: 15, latest_version: '3.1.2',
    last_published_at: '2026-04-22T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[8],
    author: DC_ORG,
  },
  {
    id: 'pkg-17', name: 'create-dc-plugin', scope: null,
    description: 'Scaffold a new Design Canvas plugin in seconds — TypeScript, React, or vanilla JS templates.',
    category_id: 'cat-9', author_id: 'a-1',
    tags: ['scaffold', 'starter', 'template', 'official'],
    npm_url: 'https://www.npmjs.com/package/create-dc-plugin',
    repo_url: 'https://github.com/design-canvas/create-dc-plugin',
    docs_url: 'https://docs.designcanvas.dev/getting-started', issues_url: null,
    weekly_downloads: 8_900, github_stars: 420,
    bundle_size_gzip: null, license: 'MIT', has_types: false,
    open_issues_count: 4, latest_version: '1.2.0',
    last_published_at: '2026-04-10T00:00:00Z', metrics_updated_at: now,
    created_at: now, updated_at: now,
    category: MOCK_CATEGORIES[8],
    author: DC_ORG,
  },
];
